Repository Node-23/bet_app, pull requests merged in 2021-08, with the labels that each got.

#14 Bettor
  src/main/java/com/bet/Model/Bet.java
  src/main/java/com/bet/Model/Bettor.java
Labels: enhancement

#13 uniqueCard Created
  src/main/java/com/bet/Model/uniqueCard.java
Labels: enhancement

#16 Add actionListeners to all JMenuItems in mainView and RegisterView created
  src/main/java/com/bet/App.java
  src/main/java/com/bet/View/MainView.java
  src/main/java/com/bet/View/RegisterView.java
Labels: enhancement

#19 Created all the menuItems windows and linked them with the actionListerners
  src/main/java/com/bet/Model/uniqueCard.java
  src/main/java/com/bet/View/MainView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/EditBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/EndBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/ListBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/NewBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/DeleteItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/EditItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/ListItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
  src/main/java/com/bet/View/MenuItemViews/DrawMenuViews/DrawItemView.java
  src/main/java/com/bet/View/MenuItemViews/DrawMenuViews/ListDrawItemView.java
  src/main/java/com/bet/View/MenuItemViews/HelpMenuViews/AboutItemView.java
  src/main/java/com/bet/View/MenuItemViews/HelpMenuViews/HowToUseItemView.java
Labels: enhancement

#20 EditBet,DeleteItem and EditItem removed due to a project design review
  src/main/java/com/bet/View/MainView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/EditBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/DeleteItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/EditItemView.java
Labels: enhancement

#21 Register bettors view
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: enhancement

#24 Register view implemented
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: enhancement

#23 Data base added to project
  .gitignore
  pom.xml
  src/main/java/com/bet/App.java
  src/main/java/com/bet/Service/Database/DBConnection.java
  src/main/java/com/bet/View/MainView.java
Labels: Feature

#22 Bettors list view done
  src/main/java/com/bet/Service/JTableButtonServices/DeleteButtonEditor.java
  src/main/java/com/bet/Service/JTableButtonServices/DeleteButtonRenderer.java
  src/main/java/com/bet/Service/JTableButtonServices/EditButtonEditor.java
  src/main/java/com/bet/Service/JTableButtonServices/EditButtonRenderer.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/ListItemView.java
Labels: enhancement

#25 Data base
  src/main/java/com/bet/Service/Database/DBCreateTables.java
  src/main/java/com/bet/View/MainView.java
Labels: enhancement

#26 RegisterItemView changed
  src/main/java/com/bet/App.java
  src/main/java/com/bet/Service/Database/DBCreateTables.java
  src/main/java/com/bet/View/MainView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: enhancement

#32 Cpf validation
  src/main/java/com/bet/Service/CPFValidation.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: enhancement

#33 Now only name and cpf are mandatory
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: documentation

#36 Register
  src/main/java/com/bet/App.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: bug

#37 The connection with the DB is made only once
  src/main/java/com/bet/App.java
  src/main/java/com/bet/Service/Database/DBConnection.java
  src/main/java/com/bet/View/MainView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/EndBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/ListBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/NewBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/ListItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
  src/main/java/com/bet/View/MenuItemViews/DrawMenuViews/DrawItemView.java
  src/main/java/com/bet/View/MenuItemViews/DrawMenuViews/ListDrawItemView.java
  src/main/java/com/bet/View/MenuItemViews/HelpMenuViews/AboutItemView.java
  src/main/java/com/bet/View/MenuItemViews/HelpMenuViews/HowToUseItemView.java
Labels: bug

#41 DB registration is made by controller files now
  src/main/java/com/bet/Controller/Bettor/BDRegistration.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: enhancement

#40 Bets
  src/main/java/com/bet/Service/CPFValidation.java
  src/main/java/com/bet/Service/Database/DBConnection.java
  src/main/java/com/bet/Service/Database/DBCreateTables.java
  src/main/java/com/bet/View/MainView.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/NewBetItemView.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/RegisterItemView.java
Labels: documentation

#42 ListItemView now is connected with database
  src/main/java/com/bet/Controller/Bettor/BettorList.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/ListItemView.java
Labels: Feature

#44 Delete button in ListItemView is working now
  src/main/java/com/bet/Controller/Bettor/BettorList.java
  src/main/java/com/bet/Controller/Bettor/DeleteBettor.java
  src/main/java/com/bet/Service/JTableButtonServices/DeleteButtonEditor.java
  src/main/java/com/bet/View/MenuItemViews/BettorMenuViews/ListItemView.java
Labels: enhancement

#45 Data base
  src/main/java/com/bet/App.java
  src/main/java/com/bet/Controller/Bettor/BDRegistration.java
  src/main/java/com/bet/Controller/Bettor/BettorList.java
  src/main/java/com/bet/Service/Database/DBConnection.java
  src/main/java/com/bet/Service/Database/DBCreation.java
  src/main/java/com/bet/View/MenuItemViews/BetMenuViews/NewBetItemView.java
Labels: Feature
